### ISSUE TITLE
why do  i did not find bower-asset/jstree: ~3?

### ISSUE THREAD

**Issue by culiangfanzi** [yii-dream-team/yii2-jstree#4]
when i Installed the package ,the composer referred me that  ：
Problem 1
    - yii-dream-team/yii2-jstree dev-master requires bower-asset/jstree ~3 -> no matching package found.
    - yii-dream-team/yii2-jstree 1.0.0 requires bower-asset/jstree ~3 -> no matching package found.
    - Installation request for yii-dream-team/yii2-jstree \* -> satisfiable by yii-dream-team/yii2-jstree[1.0.0, dev-master].

How do i fix this problem???

**Comment by metalagman** [comment]
To use bower assets you need to install composer plugin:

``` sh
composer global require "fxp/composer-asset-plugin:~1.0.3"
```

**Comment by BioSin** [comment]
And always check your "fxp/composer-asset-plugin:~1.0.3" plugn version, because he's updated from time to time.
